# Generated by Django 4.2.1 on 2023-05-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='invested_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
