# Generated by Django 4.2.1 on 2023-05-30 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_wallet_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
