# Generated by Django 4.2.1 on 2023-05-31 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='last_modified_by',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
