# Generated by Django 4.2.1 on 2023-05-24 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityTracker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('msg', models.CharField(default='NA', max_length=255)),
                ('ref', models.CharField(default='NA', max_length=255)),
                ('url', models.URLField(default='NA', max_length=255)),
                ('type', models.CharField(default='NA', max_length=64)),
                ('is_notification', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ActivityTrackerUser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lawfirm_activity_app',
            },
        ),
    ]
