# Generated by Django 4.2.1 on 2023-06-01 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alter_activitytracker_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitytracker',
            old_name='is_notification',
            new_name='is_transaction',
        ),
    ]
