# Generated by Django 4.2.1 on 2023-06-08 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_rename_is_notification_activitytracker_is_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitytracker',
            old_name='is_transaction',
            new_name='is_activity',
        ),
    ]
