# Generated by Django 4.2.1 on 2023-07-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_rename_is_transaction_activitytracker_is_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitytracker',
            name='type',
            field=models.CharField(choices=[('WALLET', 'WALLET'), ('CHAT', 'CHAT'), ('INVESTMENT', 'INVESTMENT'), ('MAIL', 'MAIL'), ('NA', 'NA')], default='NA', max_length=64),
        ),
    ]
