# Generated by Django 4.2.1 on 2023-06-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='my_usr',
            field=models.CharField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
