# Generated by Django 4.2.1 on 2023-05-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mauth', '0002_customuser_is_phone_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_aadhar_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_bank_acc_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_pan_verified',
            field=models.BooleanField(default=False),
        ),
    ]
