# Generated by Django 4.2.1 on 2023-06-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mauth', '0002_customuser_my_usr_customuser_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='my_usr',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_anytime_withdrawal_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_fixedroi_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_marketplace_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rc_risk',
            field=models.CharField(choices=[('LOW', 'LOW'), ('MODERATE', 'MODERATE'), ('HIGH', 'HIGH')], default='LOW', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='special_plan_exist',
            field=models.BooleanField(default=False),
        ),
    ]
