# Generated by Django 4.2.1 on 2023-06-28 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mauth', '0003_remove_customuser_my_usr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='email address'),
        ),
    ]
