# Generated by Django 4.2.1 on 2023-05-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mauth', '0003_customuser_is_aadhar_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
