# Generated by Django 4.2.1 on 2023-05-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mauth', '0004_alter_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('MOBILE VERIFICATION', 'MOBILE VERIFICATION'), ('PAN VERIFICATION', 'PAN VERIFICATION'), ('AADHAR VERIFICATION', 'AADHAR VERIFICATION'), ('BANK VERIFICATION', 'BANK VERIFICATION'), ('ACTIVE', 'ACTIVE')], default='MOBILE VERIFICATION'),
        ),
    ]
