# Generated by Django 4.2.1 on 2023-05-18 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mauth', '0005_customuser_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='phone',
            new_name='mobile',
        ),
    ]
