# Generated by Django 4.2.1 on 2023-07-03 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mauth', '0006_customuser_pan_api_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='registration_type',
            field=models.CharField(choices=[('SELF', 'SELF'), ('PARTNER', 'PARTNER'), ('ADMIN', 'ADMIN')], default='SELF'),
        ),
    ]
