# Generated by Django 4.2.1 on 2023-05-18 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mauth', '0006_rename_phone_customuser_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_phone_verified',
            new_name='is_mobile_verified',
        ),
    ]
