# Generated by Django 4.2.1 on 2023-05-19 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mauth', '0007_rename_is_phone_verified_customuser_is_mobile_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='aadhar',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='bank_acc',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pan',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
