# Generated by Django 4.2.1 on 2023-05-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mauth', '0008_alter_customuser_aadhar_alter_customuser_bank_acc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('MOBILE_VERIFICATION', 'MOBILE_VERIFICATION'), ('PAN_VERIFICATION', 'PAN_VERIFICATION'), ('AADHAR_VERIFICATION', 'AADHAR_VERIFICATION'), ('BANK_VERIFICATION', 'BANK_VERIFICATION'), ('ACTIVE', 'ACTIVE')], default='MOBILE_VERIFICATION'),
        ),
    ]
