# Generated by Django 4.2.1 on 2023-05-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mauth', '0009_alter_customuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('MOBILE_VERIFICATION', 'MOBILE_VERIFICATION'), ('PAN_VERIFICATION', 'PAN_VERIFICATION'), ('AADHAAR_VERIFICATION', 'AADHAAR_VERIFICATION'), ('BANK_VERIFICATION', 'BANK_VERIFICATION'), ('ACTIVE', 'ACTIVE')], default='MOBILE_VERIFICATION'),
        ),
    ]
