# Generated by Django 4.2.1 on 2023-07-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mauth', '0009_rename_activity_loghistory_activities'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loghistory',
            old_name='location',
            new_name='lat',
        ),
        migrations.AddField(
            model_name='loghistory',
            name='browser',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loghistory',
            name='long',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
