# Generated by Django 4.2.1 on 2023-07-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mauth', '0010_rename_location_loghistory_lat_loghistory_browser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='company',
            new_name='company_gst',
        ),
        migrations.AddField(
            model_name='customuser',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='company_pan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
