# Generated by Django 4.2.1 on 2023-05-19 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mauth', '0010_alter_customuser_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='aadhar',
            new_name='aadhaar',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='is_aadhar_verified',
            new_name='is_aadhaar_verified',
        ),
    ]
