# Generated by Django 4.2.1 on 2023-07-10 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mauth', '0011_rename_company_customuser_company_gst_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='company_name',
            new_name='company',
        ),
    ]
