# Generated by Django 4.2.1 on 2023-05-20 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mauth', '0012_customuser_bank_ifsc'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tnc',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
