# Generated by Django 4.2.1 on 2023-07-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mauth', '0013_customuser_nature'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='aadhaar_verify_data',
            field=models.CharField(blank=True, null=True),
        ),
    ]
