# Generated by Django 4.2.1 on 2023-05-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mauth', '0013_customuser_is_email_verified_customuser_tnc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='aadhaar_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bank_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pan_name',
            field=models.CharField(blank=True, null=True),
        ),
    ]
