# Generated by Django 4.2.1 on 2023-07-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mauth', '0014_customuser_aadhaar_verify_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='penny_trial_left',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
    ]
