# Generated by Django 4.2.1 on 2023-05-20 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mauth', '0014_customuser_aadhaar_name_customuser_bank_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='tnc',
            new_name='is_tnc_accepted',
        ),
    ]
