# Generated by Django 4.2.1 on 2023-07-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mauth', '0015_customuser_penny_trial_left_alter_customuser_email'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='customuser',
        #     name='email',
        #     field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        # ),
    ]
