# Generated by Django 4.2.1 on 2023-07-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mauth', '0016_alter_customuser_email'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='customuser',
        #     name='email',
        #     field=models.EmailField(max_length=254, null=True, unique=True),
        # ),
    ]
