# Generated by Django 4.2.1 on 2023-05-20 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mauth', '0016_customuser_account_holder_name_customuser_bank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='account_holder_name',
            new_name='acc_holder_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='bank',
        ),
    ]
