# Generated by Django 4.2.1 on 2023-05-23 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mauth', '0019_alter_customuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email',
        ),
    ]
