# Generated by Django 4.2.1 on 2023-05-25 07:00

import apps.mauth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mauth', '0022_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='selfie',
            field=models.ImageField(blank=True, null=True, upload_to=apps.mauth.models.upload_selfie),
        ),
    ]
