# Generated by Django 4.2.1 on 2023-05-25 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mauth', '0023_customuser_selfie'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='aggregator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
