# Generated by Django 4.2.1 on 2023-05-29 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mauth', '0025_customuser_city_customuser_country_customuser_state_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='zip_code',
            new_name='company',
        ),
        migrations.AddField(
            model_name='customuser',
            name='pincode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
