# Generated by Django 4.2.1 on 2023-05-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mauth', '0027_alter_customuser_email_alter_customuser_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('INVESTOR', 'INVESTOR'), ('PARTNER', 'PARTNER'), ('ADMIN', 'ADMIN')], default='INVESTOR'),
        ),
    ]
