# Generated by Django 4.2.1 on 2023-05-31 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mauth', '0029_alter_customuser_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='aggregator',
            new_name='partner',
        ),
    ]
