# Generated by Django 4.2.1 on 2023-06-14 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mauth', '0030_rename_aggregator_customuser_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_anytime_withdrawal_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_fixedroi_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_marketplace_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
