# Generated by Django 4.2.1 on 2023-06-16 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mauth', '0031_customuser_is_anytime_withdrawal_allowed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='special_plan_exist',
            field=models.BooleanField(default=False),
        ),
    ]
