# Generated by Django 4.2.1 on 2023-06-17 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mauth', '0032_customuser_special_plan_exist'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rc_risk',
            field=models.CharField(choices=[('LOW', 'LOW'), ('MODERATE', 'MODERATE'), ('HIGH', 'HIGH')], default='LOW', max_length=255),
        ),
    ]
