# Generated by Django 4.2.1 on 2023-06-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mauth', '0034_risklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
