# Generated by Django 4.2.1 on 2023-06-24 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mauth', '0035_customuser_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risklog',
            name='updated_risk',
            field=models.CharField(choices=[('LOW', 'LOW'), ('MODERATE', 'MODERATE'), ('HIGH', 'HIGH')], default='LOW', max_length=255),
        ),
    ]
