# Generated by Django 4.2.1 on 2023-06-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='medium',
            field=models.CharField(choices=[('EMAIL', 'EMAIL'), ('CALL', 'CALL')], default='EMAIL', max_length=255),
        ),
    ]
