# Generated by Django 4.2.1 on 2023-06-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpline', '0004_complaint_complaint_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
