# Generated by Django 4.2.1 on 2023-06-22 12:23

import apps.helpline.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpline', '0005_complaint_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.helpline.models.Complaint.upload_image),
        ),
    ]
