# Generated by Django 4.2.1 on 2023-07-07 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpline', '0006_complaint_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='medium',
        ),
    ]
