# Generated by Django 4.2.1 on 2023-05-26 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('loan_amount', models.IntegerField()),
                ('interest_rate', models.CharField(max_length=255)),
                ('repayment_terms', models.CharField(blank=True, max_length=1000, null=True)),
                ('installments', models.CharField(blank=True, max_length=1000)),
                ('collateral', models.CharField(max_length=255)),
                ('late_pay_penalties', models.CharField(blank=True, max_length=255, null=True)),
                ('prepayment_options', models.CharField(blank=True, max_length=255, null=True)),
                ('default_remedies', models.CharField(blank=True, max_length=1000, null=True)),
                ('privacy', models.CharField(blank=True, max_length=1000, null=True)),
                ('governing_law', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='loanform',
            name='loan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='loans.loan'),
        ),
    ]
