# Generated by Django 4.2.1 on 2023-05-30 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0002_loan_loanform_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Indicates the time when the record was created', null=True, verbose_name='Published On'),
        ),
        migrations.AddField(
            model_name='loan',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Indicates the user who created this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loan',
            name='is_record_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='last_modified_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Indicates the time when the record was last modified', null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, help_text='Indicates the user who last modified this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanform',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Indicates the time when the record was created', null=True, verbose_name='Published On'),
        ),
        migrations.AddField(
            model_name='loanform',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Indicates the user who created this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanform',
            name='is_record_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='loanform',
            name='last_modified_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Indicates the time when the record was last modified', null=True),
        ),
        migrations.AddField(
            model_name='loanform',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, help_text='Indicates the user who last modified this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
    ]
