# Generated by Django 4.2.1 on 2023-05-31 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0003_loan_created_loan_created_by_loan_is_record_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='borrower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='borrower', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loan',
            name='investor',
            field=models.ManyToManyField(related_name='investor', to=settings.AUTH_USER_MODEL),
        ),
    ]
