# Generated by Django 4.2.1 on 2023-06-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_loan_loan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_id',
            field=models.UUIDField(default='6455e0d53aa643a285151d1b38a8ce7e', editable=False),
        ),
    ]
