# Generated by Django 4.2.1 on 2023-06-08 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0007_alter_loan_loan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_id',
            field=models.UUIDField(default='7ea1f0fb08bf4b1ca06080095afa0c23', editable=False),
        ),
    ]
