# Generated by Django 4.2.1 on 2023-06-08 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0008_alter_loan_loan_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='loan_id',
        ),
    ]
