# Generated by Django 4.2.1 on 2023-06-08 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0009_remove_loan_loan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loan_id',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
