# Generated by Django 4.2.1 on 2023-06-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0012_loan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_amount',
            field=models.CharField(default='200000', max_length=100),
        ),
    ]
