# Generated by Django 4.2.1 on 2023-06-09 06:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0016_investmentplan_investors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentplan',
            name='investors',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
