# Generated by Django 4.2.1 on 2023-06-09 07:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0018_rename_investor_loan_investors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='investors',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
