# Generated by Django 4.2.1 on 2023-06-12 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0023_investmentrequest_loan_alter_investmentrequest_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentrequest',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='loan_borrower', to=settings.AUTH_USER_MODEL),
        ),
    ]
