# Generated by Django 4.2.1 on 2023-06-15 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0024_investmentrequest_borrower'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentplan',
            name='allowed_investor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='allowed_investor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investmentplan',
            name='is_special_plan',
            field=models.BooleanField(default=False),
        ),
    ]
