# Generated by Django 4.2.1 on 2023-06-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0025_investmentplan_allowed_investor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentplan',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
