# Generated by Django 4.2.1 on 2023-06-17 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0026_investmentplan_is_primary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoanForm',
        ),
    ]
