# Generated by Django 4.2.1 on 2023-06-17 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0028_rename_loan_loanapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplication',
            name='loan_id',
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='borrower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='application_borrower', to=settings.AUTH_USER_MODEL),
        ),
    ]
