# Generated by Django 4.2.1 on 2023-06-19 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0031_loanapplication_investmentrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('is_record_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Indicates the time when the record was created', null=True, verbose_name='Published On')),
                ('last_modified_at', models.DateTimeField(auto_now_add=True, help_text='Indicates the time when the record was last modified', null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('loan_amount', models.IntegerField()),
                ('interest_rate', models.IntegerField()),
                ('repayment_terms', models.CharField(max_length=255)),
                ('installments', models.IntegerField()),
                ('collateral', models.CharField(max_length=255)),
                ('late_pay_penalties', models.CharField(max_length=255)),
                ('prepayment_options', models.CharField(max_length=255)),
                ('default_remedies', models.CharField(max_length=255)),
                ('privacy', models.CharField(max_length=255)),
                ('governing_law', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('UNDER PROCESS', 'UNDER PROCESS'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], default='UNDER PROCESS', max_length=255)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loans.loanapplication')),
                ('created_by', models.ForeignKey(blank=True, help_text='Indicates the user who created this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, help_text='Indicates the user who last modified this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
