# Generated by Django 4.2.1 on 2023-06-19 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0032_bid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('is_record_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Indicates the time when the record was created', null=True, verbose_name='Published On')),
                ('last_modified_at', models.DateTimeField(auto_now_add=True, help_text='Indicates the time when the record was last modified', null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('due_date', models.DateField()),
                ('amount', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('paid_date', models.DateField()),
                ('payment_reference', models.CharField(max_length=255)),
                ('late_fee', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(blank=True, help_text='Indicates the user who created this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, help_text='Indicates the user who last modified this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('is_record_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Indicates the time when the record was created', null=True, verbose_name='Published On')),
                ('last_modified_at', models.DateTimeField(auto_now_add=True, help_text='Indicates the time when the record was last modified', null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('loan_amount', models.IntegerField()),
                ('loan_id', models.CharField(blank=True, max_length=1000, unique=True)),
                ('interest_rate', models.CharField(max_length=255)),
                ('repayment_terms', models.CharField(blank=True, max_length=1000, null=True)),
                ('collateral', models.CharField(blank=True, max_length=255, null=True)),
                ('late_pay_penalties', models.CharField(blank=True, max_length=255, null=True)),
                ('prepayment_options', models.CharField(blank=True, max_length=255, null=True)),
                ('default_remedies', models.CharField(blank=True, max_length=1000, null=True)),
                ('privacy', models.CharField(blank=True, max_length=1000, null=True)),
                ('governing_law', models.CharField(blank=True, max_length=1000, null=True)),
                ('status', models.CharField(choices=[('APPLIED', 'APPLIED'), ('UNDER BIDDING', 'UNDER BIDDING'), ('CLOSED', 'CLOSED')], default='APPLIED', max_length=255)),
                ('borrower', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='final_loan_borrower', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, help_text='Indicates the user who created this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('installments', models.ManyToManyField(to='loans.installment')),
                ('investors', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, help_text='Indicates the user who last modified this record', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='installment',
            name='parent_loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loans.loan'),
        ),
    ]
