# Generated by Django 4.2.1 on 2023-06-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0034_investmentrequest_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentplan',
            name='min_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investmentplan',
            name='principal_type',
            field=models.CharField(choices=[('FIXED', 'FIXED'), ('VARIABLE', 'VARIABLE')], default='FIXED', max_length=255),
        ),
        migrations.AddField(
            model_name='loan',
            name='type',
            field=models.CharField(choices=[('FIXED ROI', 'FIXED ROI'), ('ANYTIME WITHDRAWAL', 'ANYTIME WITHDRAWAL')], default='FIXED ROI', max_length=255),
        ),
    ]
