# Generated by Django 4.2.1 on 2023-06-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0035_investmentplan_min_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentplan',
            name='investing_limit',
            field=models.IntegerField(null=True),
        ),
    ]
