# Generated by Django 4.2.1 on 2023-06-20 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0037_investmentrequest_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='investors',
        ),
        migrations.AddField(
            model_name='loan',
            name='investor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='final_loan_investor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='installment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('PAID', 'PAID')], default='PENDING', max_length=255),
        ),
    ]
