# Generated by Django 4.2.1 on 2023-06-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0038_remove_loan_investors_loan_investor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentrequest',
            name='type',
            field=models.CharField(choices=[('FIXED ROI', 'FIXED ROI'), ('ANYTIME WITHDRAWAL', 'ANYTIME WITHDRAWAL'), ('LOAN', 'LOAN')], default='FIXED ROI', max_length=255),
        ),
    ]
