# Generated by Django 4.2.1 on 2023-06-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0039_investmentrequest_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='type',
            field=models.CharField(choices=[('FIXED ROI', 'FIXED ROI'), ('ANYTIME WITHDRAWAL', 'ANYTIME WITHDRAWAL'), ('LOAN', 'LOAN')], default='FIXED ROI', max_length=255),
        ),
    ]
