# Generated by Django 4.2.1 on 2023-06-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0040_alter_loan_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentrequest',
            name='tenure',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='tenure',
            field=models.IntegerField(null=True),
        ),
    ]
