# Generated by Django 4.2.1 on 2023-06-21 06:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0042_alter_installment_late_fee_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvestmentPlan',
            new_name='InvestmentProduct',
        ),
    ]
