# Generated by Django 4.2.1 on 2023-06-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0044_remove_investmentrequest_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='installment',
            old_name='amount',
            new_name='total_amount',
        ),
        migrations.AddField(
            model_name='installment',
            name='interest',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='installment',
            name='principal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
