# Generated by Django 4.2.1 on 2023-06-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0045_rename_amount_installment_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='interest_calculation_type',
            field=models.CharField(choices=[('DAILY', 'DAILY'), ('MONTHLY', 'MONTHLY'), ('QUARTERLY', 'QUARTELY'), ('ANNUALLY', 'ANNUALLY')], default='MONTHLY', max_length=255),
        ),
    ]
