# Generated by Django 4.2.1 on 2023-06-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0047_investmentproduct_minimum_locking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('ONGOING', 'ONGOING'), ('PAID', 'PAID')], default='ONGOING', max_length=255),
        ),
    ]
