# Generated by Django 4.2.1 on 2023-06-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0048_alter_loan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='installments',
            field=models.ManyToManyField(blank=True, to='loans.installment'),
        ),
    ]
