# Generated by Django 4.2.1 on 2023-06-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0049_alter_loan_installments'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentproduct',
            name='plan_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
