# Generated by Django 4.2.1 on 2023-06-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0050_investmentproduct_plan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='plan_id',
            field=models.CharField(blank=True, max_length=1000, unique=True),
        ),
    ]
