# Generated by Django 4.2.1 on 2023-06-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0053_loanapplication_tenure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='interest_calculation_type',
        ),
        migrations.AlterField(
            model_name='loan',
            name='repayment_terms',
            field=models.CharField(blank=True, choices=[('DAILY', 'DAILY'), ('MONTHLY', 'MONTHLY'), ('QUARTERLY', 'QUARTELY'), ('ANNUALLY', 'ANNUALLY')], default='MONTHLY', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='repayment_terms',
            field=models.CharField(blank=True, choices=[('DAILY', 'DAILY'), ('MONTHLY', 'MONTHLY'), ('QUARTERLY', 'QUARTELY'), ('ANNUALLY', 'ANNUALLY')], max_length=1000, null=True),
        ),
    ]
