# Generated by Django 4.2.1 on 2023-06-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0054_remove_loan_interest_calculation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='type',
            field=models.CharField(choices=[('OPEN bID', 'OPEN BID'), ('CLOSE BID', 'CLOSE BID')], default='OPEN BID', max_length=100),
        ),
    ]
