# Generated by Django 4.2.1 on 2023-06-24 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0056_alter_loanapplication_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investmentrequest',
            old_name='amount',
            new_name='loan_amount',
        ),
    ]
