# Generated by Django 4.2.1 on 2023-06-24 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0057_rename_amount_investmentrequest_loan_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsAndCondition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tnc', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='tnc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='loans.termsandcondition'),
        ),
    ]
