# Generated by Django 4.2.1 on 2023-06-24 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0058_termsandcondition_loanapplication_tnc'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentproduct',
            name='tnc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='loans.termsandcondition'),
        ),
        migrations.AddField(
            model_name='loan',
            name='tnc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='loans.termsandcondition'),
        ),
    ]
