# Generated by Django 4.2.1 on 2023-06-26 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0060_loanapplication_credit_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplication',
            name='credit_score',
        ),
    ]
