# Generated by Django 4.2.1 on 2023-06-30 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0061_remove_loanapplication_credit_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentproduct',
            name='invested_amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='investmentproduct',
            name='investors',
        ),
        migrations.AddField(
            model_name='investmentproduct',
            name='investors',
            field=models.IntegerField(default=0),
        ),
    ]
