# Generated by Django 4.2.1 on 2023-06-30 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0063_loan_is_tnc_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='loans.investmentproduct'),
        ),
    ]
