# Generated by Django 4.2.1 on 2023-06-30 07:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0064_loan_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentproduct',
            name='allowed_investor',
        ),
        migrations.AddField(
            model_name='investmentproduct',
            name='allowed_investor',
            field=models.ManyToManyField(blank=True, null=True, related_name='allowed_investor', to=settings.AUTH_USER_MODEL),
        ),
    ]
