# Generated by Django 4.2.1 on 2023-06-30 09:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0066_investmentproduct_investors_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentproduct',
            name='allowed_investor',
            field=models.ManyToManyField(related_name='allowed_investor', to=settings.AUTH_USER_MODEL),
        ),
    ]
