# Generated by Django 4.2.1 on 2023-07-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0069_alter_product_interest_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='min_amount',
            field=models.IntegerField(),
        ),
    ]
