# Generated by Django 4.2.1 on 2023-07-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0070_alter_product_min_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='max_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
