# Generated by Django 4.2.1 on 2023-07-01 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0071_alter_product_max_amount_alter_product_min_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tenure',
        ),
    ]
