# Generated by Django 4.2.1 on 2023-07-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0073_product_max_tenure_product_min_tenure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('FIXED ROI', 'FIXED ROI'), ('ANYTIME WITHDRAWAL', 'ANYTIME WITHDRAWAL'), ('SIP', 'SIP')], default='FIXED ROI', max_length=255),
        ),
    ]
