# Generated by Django 4.2.1 on 2023-07-03 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0075_investment_payment_investment_installments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='product',
        ),
    ]
