# Generated by Django 4.2.1 on 2023-07-04 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0076_remove_payment_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='product_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
