# Generated by Django 4.2.1 on 2023-07-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0077_payment_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Param',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('min_amount', models.IntegerField()),
                ('max_amount', models.IntegerField()),
                ('min_tenure', models.IntegerField()),
                ('max_tenure', models.IntegerField()),
                ('min_interest', models.FloatField()),
                ('max_interest', models.FloatField()),
            ],
        ),
    ]
