# Generated by Django 4.2.1 on 2023-07-07 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0079_newproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('PAID', 'PAID')], default='PENDING', max_length=100),
        ),
    ]
