# Generated by Django 4.2.1 on 2023-07-07 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0080_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loans.newproduct'),
        ),
    ]
