# Generated by Django 4.2.1 on 2023-07-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0081_alter_investment_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='interest_payment',
            field=models.CharField(choices=[('DAILY', 'DAILY'), ('MONTHLY', 'MONTHLY'), ('QUARTERLY', 'QUARTERLY'), ('ANNUALLY', 'ANNUALLY')], default='MONTHLY', max_length=100),
        ),
    ]
