# Generated by Django 4.2.1 on 2023-06-08 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_alter_transaction_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.UUIDField(default='cffa1d4de3e84260a0e20cfa2aaadc65', editable=False, unique=True),
        ),
    ]
