# Generated by Django 4.2.1 on 2023-06-08 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_alter_transaction_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.UUIDField(default='76ba9494b04f4b2c9c10d6614f5ec01b', editable=False, unique=True),
        ),
    ]
