# Generated by Django 4.2.1 on 2023-06-08 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_alter_transaction_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.UUIDField(default='7270461bd00b48e6bc8f58bc6dfe8279', editable=False, unique=True),
        ),
    ]
