# Generated by Django 4.2.1 on 2023-06-08 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_alter_transaction_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.UUIDField(default='8bb5cc8b28c04ed0bd09876227ffe139', editable=False, unique=True),
        ),
    ]
