# Generated by Django 4.2.1 on 2023-06-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0016_alter_bankaccount_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='earnings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
