# Generated by Django 4.2.1 on 2023-06-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0017_wallet_earnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='ref_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(blank=True, choices=[('SUCCESS', 'SUCCESS'), ('PENDING', 'PENDING'), ('FAILED', 'FAILED')], max_length=100, null=True),
        ),
    ]
