# Generated by Django 4.2.1 on 2023-06-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0018_transaction_ref_id_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='penny_drop_utr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
