# Generated by Django 4.2.1 on 2023-06-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0021_alter_bankaccount_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(blank=True, choices=[('ADD FUNDS', 'ADD FUNDS'), ('WITHDREW FUNDS', 'WITHDREW FUNDS'), ('INVESTMENT', 'INVESTMET'), ('INTEREST', 'INTEREST'), ('REPAYMENT', 'REPAYMENT')], max_length=100, null=True),
        ),
    ]
