# Generated by Django 4.2.1 on 2023-06-30 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0022_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(blank=True, choices=[('ADD FUNDS', 'ADD FUNDS'), ('WITHDREW FUNDS', 'WITHDREW FUNDS'), ('INVESTMENT', 'INVESTMET'), ('INTEREST', 'INTEREST'), ('REPAYMENT', 'REPAYMENT'), ('LOAN', 'LOAN')], max_length=100, null=True),
        ),
    ]
